### ISSUE TITLE
`unicode` and `json.loads/json.dumps` disagree on floats

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#361]
>>> import json
    >>> json.loads(json.dumps({2/3.: 0}))
    {u'0.6666666666666666': 0}
    >>> unicode(2/3.)
    u'0.666666666667'

When creating crosscat categorical column metadata in `crosscat_categorical_metadata`, we may inadvertently create a code_to_value dict keyed by floats -- because sqlite3 returns them for some reason -- instead of strings, and then we get whatever encoding json uses.  Then `_crosscat_data` tries to look up a value in the code_to_value data obtained by passing the float through `unicode` rather than whatever the json library uses.

The easy fix for this is to just call `unicode` when constructing the table.  But we probably *also* want to modify the queries in `_crosscat_data` and `_crosscat_metadata_categorical` to explicitly request that we get the *string* values in the table, not parsed as floats as sqlite3 will helpfully do for us.

(Belhal tripped over this issue in a table where the column should have been numerical, not categorical -- but that's a separate issue.  Even if the column is made categorical, this bug remains.)

**Comment by madeleineth** [comment]
For what it's worth: `unicode` (and `str`) should not be used to encode Python objects in an invertible way. If you want to encode them invertibly, use `repr`. `json.dumps` and `repr` give an exact (though not unique) string representation. `unicode` and `str` do not.

    >>> json.dumps(2.0/3.0)
    '0.6666666666666666'
    >>> repr(2.0/3.0)
    '0.6666666666666666'
    >>> str(2.0/3.0)
    '0.666666666667'
    >>> float(str(2.0/3.0)) - 2.0/3.0
    3.333999742949345e-13
    >>> float(repr(2.0/3.0)) - 2.0/3.0
    0.0
    >>> import sys
    >>> sys.version
    '2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]'

**Comment by riastradh-probcomp** [comment]
Date: Mon, 18 Jan 2016 09:46:14 -0800
   From: Madeleine Thompson <notifications@github.com>

   For what it's worth: `unicode` (and `str`) should not be used to
   encode Python objects in an invertible way. If you want to encode
   them invertibly, use `repr`. `json.dumps` and `repr` give an exact
   (though not unique) string representation. `unicode` and `str` do
   not.

In this case, the only type of object that should be fed in is either
a str or unicode, or perhaps only a unicode, in which case that's not
an issue.  That sqlite3 will hand us a float instead is part of what
causes this.  Doing

   SELECT CAST(x AS TEXT) ...

instead of

   SELECT x ...

to get the values in question should fix it.

**Comment by BelhalK** [comment]
Did we fix that bug?
Still have an issue (on a different dataset but same error message, cf screenshot)
![capture d ecran 2016-02-02 a 17 15 07](https://cloud.githubusercontent.com/assets/15817944/12768872/153b4474-c9e1-11e5-89cb-032bdf68c435.png)

**Comment by riastradh-probcomp** [comment]
Date: Tue, 02 Feb 2016 16:13:57 -0800
   From: Belhal KARIMI <notifications@github.com>

   Did we fix that bug?
   Still have an issue (on a different dataset but same error message, cf screenshot)
   ![capture d ecran 2016-02-02 a 17 15 07](https://cloud.githubusercontent.com/assets/15817944/12768872/153b4474-c9e1-11e5-89cb-032bdf68c435.png)

It appears that you do not have the fix, from
<https://github.com/probcomp/bayeslite/commit/da13077ee7328382e04fc2cfa5aec6acaf25155d>.
I'm not sure it's been put out in a bayeslite release yet.
